package com.github.jbox.utils;

/**
 * @author jifang.zjf@alibaba-inc.com (FeiQing)
 * @version 1.0
 * @since 2018-08-09 17:23:00.
 */
public class Tony {

    public static void main(String[] args) {
        printMe();
    }

    public static void printMe() {
        System.out.println("/--------------------------------------------------\\");
        System.out.println("|             `/ssos+`       `oo/+s/`              |");
        System.out.println("|             +Ms``/Ny       yN-  /M/              |");
        System.out.println("|             hM`   +M-     .Mo    dd              |");
        System.out.println("|             hM.   -M+     :M:    dm              |");
        System.out.println("|             /M+   -M/     -M:    mh              |");
        System.out.println("|             `mm`  /M-     .M+   -M+              |");
        System.out.println("|              :M+  oMyhhhhhhNy   oM.              |");
        System.out.println("|           `/ymd/  `-.`    ``    -sddo-           |");
        System.out.println("|        `+dms:`                     `:ydo.        |");
        System.out.println("|      .sNy:                            `+ms.      |");
        System.out.println("|    `omo`                                `+m+     |");
        System.out.println("|   .mh.                                    .dh`   |");
        System.out.println("|  -No                                       `dd`  |");
        System.out.println("| `mh`    ::::::://////-    -+++++++++++++`   .Ns  |");
        System.out.println("| +M-`   `++++++///////-    .:::::::::::::     oN` |");
        System.out.println("| hm..                                         -M- |");
        System.out.println("| hd...                                        -M- |");
        System.out.println("| sN-..`                                       +N` |");
        System.out.println("| -My....                                     `dy  |");
        System.out.println("|  +Ms-...`                                   sN.  |");
        System.out.println("|   /Nh:----.`                              `sN-   |");
        System.out.println("|    `sNy:-----.``                         :dh.    |");
        System.out.println("|      .omh+--------.....`````````.....-:sdh-      |");
        System.out.println("|         :ymds+:------------------:+shdy/`        |");
        System.out.println("|            :dyyys+/:-....../+osyyyd/.            |");
        System.out.println("\\--------------------------------------------------/");
    }

    public static void printDog() {
        System.out.println("                       ::");
        System.out.println("                      :;J7, :,                        ::;7:");
        System.out.println("                      ,ivYi, ,                       ;LLLFS:");
        System.out.println("                      :iv7Yi                       :7ri;j5PL");
        System.out.println("                     ,:ivYLvr                    ,ivrrirrY2X,");
        System.out.println("                     :;r@Wwz.7r:                :ivu@kexianli.");
        System.out.println("                    :iL7::,:::iiirii:ii;::::,,irvF7rvvLujL7ur");
        System.out.println("                   ri::,:,::i:iiiiiii:i:irrv177JX7rYXqZEkvv17");
        System.out.println("                ;i:, , ::::iirrririi:i:::iiir2XXvii;L8OGJr71i");
        System.out.println("              :,, ,,:   ,::ir@mingyi.irii:i:::j1jri7ZBOS7ivv,");
        System.out.println("                 ,::,    ::rv77iiiriii:iii:i::,rvLq@huhao.Li");
        System.out.println("             ,,      ,, ,:ir7ir::,:::i;ir:::i:i::rSGGYri712:");
        System.out.println("           :::  ,v7r:: ::rrv77:, ,, ,:i7rrii:::::, ir7ri7Lri");
        System.out.println("          ,     2OBBOi,iiir;r::        ,irriiii::,, ,iv7Luur:");
        System.out.println("        ,,     i78MBBi,:,:::,:,  :7FSL: ,iriii:::i::,,:rLqXv::");
        System.out.println("        :      iuMMP: :,:::,:ii;2GY7OBB0viiii:i:iii:i:::iJqL;::");
        System.out.println("       ,     ::::i   ,,,,, ::LuBBu BBBBBErii:i:i:i:i:i:i:r77ii");
        System.out.println("      ,       :       , ,,:::rruBZ1MBBqi, :,,,:::,::::::iiriri:");
        System.out.println("     ,               ,,,,::::i:  @arqiao.       ,:,, ,:::ii;i7:");
        System.out.println("    :,       rjujLYLi   ,,:::::,:::::::::,,   ,:i,:,,,,,::i:iii");
        System.out.println("    ::      BBBBBBBBB0,    ,,::: , ,:::::: ,      ,,,, ,,:::::::");
        System.out.println("    i,  ,  ,8BMMBBBBBBi     ,,:,,     ,,, , ,   , , , :,::ii::i::");
        System.out.println("    :      iZMOMOMBBM2::::::::::,,,,     ,,,,,,:,,,::::i:irr:i:::,");
        System.out.println("    i   ,,:;u0MBMOG1L:::i::::::  ,,,::,   ,,, ::::::i:i:iirii:i:i:");
        System.out.println("    :    ,iuUuuXUkFu7i:iii:i:::, :,:,: ::::::::i:i:::::iirr7iiri::");
        System.out.println("    :     :rk@Yizero.i:::::, ,:ii:::::::i:::::i::,::::iirrriiiri::,");
        System.out.println("     :      5BMBBBBBBSr:,::rv2kuii:::iii::,:i:,, , ,,:,:i@petermu.,");
        System.out.println("          , :r50EZ8MBBBBGOBBBZP7::::i::,:::::,: :,:,::i;rrririiii::");
        System.out.println("              :jujYY7LS0ujJL7r::,::i::,::::::::::::::iirirrrrrrr:ii:");
        System.out.println("           ,:  :@kevensun.:,:,,,::::i:i:::::,,::::::iir;ii;7v77;ii;i,");
        System.out.println("           ,,,     ,,:,::::::i:iiiii:i::::,, ::::iiiir@xingjief.r;7:i,");
        System.out.println("        , , ,,,:,,::::::::iiiiiiiiii:,:,:::::::::iiir;ri7vL77rrirri::");
        System.out.println("         :,, , ::::::::i:::i:::i:i::,,,,,:,::i:i:::iir;@Secbone.ii:::");
    }

    public static void printGoku() {
        System.out.println("                                                MMMMMMM");
        System.out.println("                                                   .MMMMMMMMH");
        System.out.println("                                                     .MMMMMMMMMMM");
        System.out.println("                                                       MMMMMMMMMMMM'");
        System.out.println("                                                        'MMMMMMMMMMMMM");
        System.out.println("                                                          MMMMMMMMMMMMMMM");
        System.out.println("                                                           MMMMMMMMMMMMMMMM.");
        System.out.println("                                                            .MMMMMMMMMMMMMMMMH          H");
        System.out.println("                                                             MMMMMMMMMMMMMMMMMM          M");
        System.out.println("                                                              :MMMMMMMMMMMMMMMMMM         M");
        System.out.println("                                                              :MMMMMMMMMMMMMMMMMMMM        M");
        System.out.println("                                                               .MMMMMMMMMMMMMMMMMMMMM       M");
        System.out.println("                                                                MMMMMMMMMMMMMMMMMMMMMM:      M");
        System.out.println("                                                                MMMMMMMMMMMMMMMMMMMMMMMM      M");
        System.out.println("                                                                 HMMMMMMMMMMMMMMMMMMMMMMM     HM");
        System.out.println("                                                                 MMMMMMMMMMMMMMMMMMMMMMMMM     .I");
        System.out.println("                                                                  MMMMMMMMMMMMMMMMMMMMMMMMM     M");
        System.out.println("                                                                  'MMMMMMMMMMMMMMMMMMMMMMMMM'    M");
        System.out.println("                                                                   MMMMMMMMMMMMMMMMMMMMMMMMMM.    M");
        System.out.println("                                                                   MMMMMMMMMMMMMMMMMMMMMMMMMMMH   MM");
        System.out.println("                                                                   :MMMMMMMMMMMMMMMMMMMMMMMMMMMM   M");
        System.out.println("                                                                    MMMMMMMMMMMMMMMMMMMMMMMMMMMM.   M");
        System.out.println("                                                                    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM   M");
        System.out.println("               ..MMMMMMMMMMMMMMMMMMMMMMMMMMM:M.                     :MMMMMMMMMMMMMMMMMMMMMMMMMMMMM:  H");
        System.out.println("     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH                MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM   M");
        System.out.println("  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM   M");
        System.out.println("   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM  M");
        System.out.println("      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM. '.");
        System.out.println("         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM' M");
        System.out.println("           HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.M");
        System.out.println("              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'M");
        System.out.println("               IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:M");
        System.out.println("                 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                   .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'");
        System.out.println("                     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'");
        System.out.println("                       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                        MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                          .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                            H'                    :");
        System.out.println("                           HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                       MH                    :MM");
        System.out.println("                            :MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                   MM.                  MMMMM");
        System.out.println("                              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                M:                MMMMMMMM.");
        System.out.println("                               MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                           :M             'MMMMMMMMMMMM");
        System.out.println("                                MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                        MM           MMMMMMMMMMMMMMM");
        System.out.println("                                 .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                     MM       MMMMMMMMMMMMMMMMMMM");
        System.out.println("                                  .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                 MM    MMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                 MMMMMM             HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM               MM  MMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                       MMMM.         MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM            MMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                           MMM'       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'        MMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                             MMMM      MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                               MMMM    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:");
        System.out.println("                                 MMMM   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                   MMM  HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH");
        System.out.println("              MMMMMMMMM:            .MM  MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                MMMMMMMMMMMMMMMMMMH   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'MMMMMMMMMMMMMMMMMM.H'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMM'MMMMMMMMMMMMMMMMMMO''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'");
        System.out.println("                          MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMMMMM''MMMMMMMMMMMMMMMMM.''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'");
        System.out.println("                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM: MMMMMM.'' MMMMMMMMMMMMMMMMM'''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.");
        System.out.println("                              MMMMMMMMMMMMMMMMMMMMMMMMMMMMM' MMMMMM''':MMMMMMMMMMMMMM'M'''MMMMMMMMMMMMMMMM'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                .MMMMMMMMMMMMMMMMMMMMMMMMMMMM MMMMM''''MMMMMMMMMMMMMM'''''MMMMMMMMMMMMMMM'''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                  IMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'''''MMMMMMMMMMMMM.'''''MMMMMMMMMMMMM''''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.");
        System.out.println("                                    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'''''MMMMMMMMMMMMM''''''MMMMMMMMMMMMM''M'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                      MMMMMMMMMMMMMMMMMMMMMMMMMM'MMM'''''MMMMMMMMMMMM''M''''MMMMMMMMMMM'''M'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM           .MMMMMMMMMMMMMMMM'");
        System.out.println("                                       MMMMMMMMMMMMMMMMMM'MMMMMMM'MMM'''''MMMMMMMMMMMH'M''''MMMMMMMMMMM'''M'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'    MMMMMM");
        System.out.println("                                        'MMMMMMMMMMM'''MM'''MMMMM''.M.'''''MMMMMMMMMMM'M'''''MMMMMMMMM'''':'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH''");
        System.out.println("                                          .MMMMMMMMM'MM''M''''MMMM ''M''''''MMMMMMMMMM'M'''''MMMMMMMMM'''''M.MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'.:");
        System.out.println("                                            MMMMMMMM.'''MM''''''MMMM''M'''''''MMMMMMMM'' '''''MMMMMMMMM''''M'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'");
        System.out.println("                                             MMMMMMM.''''MM'''M'''MM''''''''''''MMMMMMM'M'''MMMMMMMMMM:''''M'MMMMMMMMMMMM'''''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:M'");
        System.out.println("                                              MMMMMM  '.M'M'''M''''MM''''''''''''MMMMMM'M'MMMMMMMMMM''''''''M'MMMMMMMMMM''''''''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                               MMMMM'M'M''M'''M'''''MMM''''''''''''MMMM'MMMMMMMMMMM'''''''''M'M MM''MMM'''MM'::''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                     .MMM'      MMMM:''M''''''M'''''MMMM''''''''''''MMMMMMMMMMMMMMMM''''''''''M'MM''MM'''M''''''''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                   'MMMMMMMMMMMMMMMMM'''M.MM''M'''''MMMMM''''''''''''MMMMMMMMMMMM''M''''''''''''MM''''''MM'''''M''MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                         MMMMMMMMMMMM''HMM'M'''M''''MMMMMMM'''''''.MMMMMMMMMMMMM'''M.'''''''''''MM'''''MM''M''''.'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                           'MMMMMMMMMM''MMMM''''M''''MMMMMMM''''MMMMMMM'''''M.''''''M'''''''''''MM''''M'M'''M'''M'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                              MMMMMMMM 'MMMM'''' M''''MM'MM .'''MMMMH'''''''''''''''''''''''''''M'''''M MM:'''''M'MMMMMMMMMMMMMMMMMMMMMMMMMMM:'");
        System.out.println("                                                MMMMMMM''H'M''''''M.''''''':''''M:M'''''''''''''''''''''''''''''''''''MM'''''M''M'MMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                                   MMMMM''MM'''''''''''''''''''''''M''''''''''''''''''''''''''''''''''MMHM'''M':'MMMMMMMMMMMMMMMMMMMMMH");
        System.out.println("                                                     MMMMM'M'''''''''''''''''''''''HMMM'''''''''''''''''''''''''''''''M''M'''M'''MMMMMMMMMMMMMMMMM:");
        System.out.println("                                                       MMMMM''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''.''M'''MMMMMMMMMMMMMM");
        System.out.println("                                                          M'''''''''':MM''''''''''''''''''''''''''''''''''''''''''''''''''M''M''MMMMMMMMMMMM");
        System.out.println("                                                          M'''''''''''M'''''''''''''''''''''''''''''''''''''''''''''''''''''M''MMMMMMMMMM");
        System.out.println("                                                         M''''''''''''''''''''''''''''''''''''''''''''''''''''''''MMM'''M'''''MMMMMMMM");
        System.out.println("                                                          M'''''''''''''''''''''''''''''''''''''''''''''''''''''''HM'.M''''''MMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                                           M''''''''''''''''''''''''''''''''''''''''''''''''''H'''MM:''''''MMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                                            HM''''''''''''''''''''''''''''''''''''''''''''''OMM:'''''''''MMMMMMMMMMMMMMMMMMM'");
        System.out.println("                                                              M:'''''''''HMMMM''''''''''''''''''''''''''''''MMMM.'''''MMMMMMMMMMMMM M");
        System.out.println("                                                               .M''''''MMO::::M''''''''''''''''''''''''''''MMMMMMMMMMMMMMMMMM.");
        System.out.println("                                                                 MM''''MMMHIHMM''''''''''''''''''''''''''MMMMMMMMMMMMMMM");
        System.out.println("                                                                  MM'''''''''''''''''''''''''''''''''''MMMMMMMMMMMMMMMMMM:");
        System.out.println("                                                                    M''''''''''''''''''''''''''''''MMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                                                     M ''''''''''''''''''''''MMMMM'''MMMMM");
        System.out.println("                                                                      MM''''''''''''''.MMMMM'''''''''MMM");
        System.out.println("                                                                       MMM''''''MMMMMM''''''''''''''''MM");
        System.out.println("                                                                       M'MMMMMMM''''''''''''''''''''''MM");
        System.out.println("                                                                       H'''''''''''''''''''''''''''''''M");
        System.out.println("                                                                      :''''''''''''''''''''''''''''''''M");
        System.out.println("                                                                 '    M'''''''''''''''''''''''''''''''':M");
        System.out.println("                                                                MM:::MM'''''''''''''''''''''''''''''''''MMM       MMMMH    H'MMMMMM:HM");
        System.out.println("                                                               MH::MMM''''''''''''''''''''''''''''''''''''''MMMM'MH::::::::::::::::::::M.");
        System.out.println("                                                        MMMMMHMH::M:MM'''''''''''''''''''''''''''''''''''''''''MM:::::::::::::::IMM':MM::M");
        System.out.println("                                                    MMM::::::M::HM':M''''''''''''''''''''''''''''''''''''''''.MH::::::::::::::MM'''''''':MM");
        System.out.println("                                               MMMH:::::::::M::MM'''''''''''''''''''''''''''''''''''''''''''MM::::::::::::::M''''''''''''''':M");
        System.out.println("                                           HMMM:::::::::::MM::::M'''''''''''''''''''''''''':MHMMMMMMMMMM''.MM:::::::::::::MI'''''''''''''''''''MM");
        System.out.println("                                          M::::::::::::::MM:::::MMM'''''''''''''''''''HMMM'''''''''''''''MM::::::::::::::M'''''''''''''''''''''''MM");
        System.out.println("                                           M:::::::::::::M:::::::MMMM:''''''''''''''MM'''''''''''''''''MM:::::::::::::::MM'''''''''''''''''''''''''MM");
        System.out.println("                                           M::::::::::::::::::::::M'''M'''''''M'''M''''''''''''''''''MM:::::::::::::::::M'''''''''''''''''''''''''''MM");
        System.out.println("                                          MH:::H::::::::::::::::::M''''''''''..'::'''''''''''''''':MM:::::::::::::::::::M''''''''''''''''''''''''''''M");
        System.out.println("                                         M:':::M:::::::::::::::::::M''''''MMM:''''''''''''''''''MMH:::::::::::::::::::::M''''''''''''''''''''''''''''M");
        System.out.println("                                        M'''M::M::::H:::::::::::::::O''''''''''''''''''''''MMMM:::::::::::::::::::::::::M''''''''''''''''''''''''''''M");
        System.out.println("                                       '.'''M:M:::::M:::::::::::::::H''''''''''''''''''''MM:::::::::::::::::::::::::::::M''''''''''''''''''''''''''''M");
        System.out.println("                                      'M''''.HM::::::M:::H:::::::::::H'''M'''''''''''MMM::::::::::::::::::::::::::::::::M'''''.''''''''''''''''''''''M");
        System.out.println("                                      M''''''M::::::::::::M:::::::::::M''M''''''''MMH:::::::::::::::::::::::::::::::::::MM'''''''''''''''''''''''''''M'");
        System.out.println("                                     M'''''''M::::::::M::::H::::::::::::'H''''''MM::::::::::::::::::::::::::::::::::::::MM'''H:''''''''''''''''''''''MHM");
        System.out.println("                                     ''''''''M:::::::::M:::::::::::::::MM ''''M:::::::::::::::::::::::::::H:::::::::::::OM'''M'''''''''''''''''''''''M'HM");
        System.out.println("                                    'M''''''H:::::::::::MM::::M:::::::::M''M::::::::::::::::::::::::::::.::::::::::::::::M''MM'''''''''''''''''''''''''''M");
        System.out.println("                                     M''''''M:::::::::::MMM:::::::::::::HM::::::::::::::::::::::::::::M::::::::::::::::::MM.MM'''''''''''''''''''''''''''MM");
        System.out.println("                                     M''''''M::::::::::::MMH::::::::::::::::::::::::::::::::::::::::MH:::::::::::::::::::M:MMM''''''''''''''''''''''''''''H'");
        System.out.println("                                     H:'''''H:::::::::::::MMM::::::::::::::::::::::::::::::::::::::M:::::::::::::::::::::::::M'''''''''''''''''''''''''''''M");
        System.out.println("                                     M'''''M:::::::::::::::HMM:::::::::::::::::::::::::::::::::::M::::::::::::::M::::::::::::MO'''''''''''''''''''''''''''''M");
        System.out.println("                                     M'''''M::::::::::::::::::M:::::::::::::::::::::::::::::::HMM:::::::::::::::::M::::::::::MM''''''''''''''''''''''''''''':M");
        System.out.println("                                     M'''''M::::::::::::::::::::::::::::::::::::::::::::HMH::::::::::::::::::::M::::M::::::::MM''''''''''''''''''''''''''''''.'");
        System.out.println("                                    M.''''.::::::::::::::::::::::::::::::::::::::::HM::::::::::::::::::::::::::::M:::MH:::::::M'''''''''''''''''''''''''''''''M");
        System.out.println("                                    M'''''M::::::::::::::::::::::::::::::::::::MM::::::::::::::::::::::::::::::::::M:::MM:::::M'''''''''''''''''''''''''''''''':");
        System.out.println("                                   .M'''''M::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M::::MM:MM''''''''''''''''''''''''''''''''M");
        System.out.println("                                   M''''''M::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M:::::HM'''''''''''''''''''''''''''''''''M");
        System.out.println("                                  'M'''''.H:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::MM::IM''''''''''''''''''''''''''''''''M");
        System.out.println("                                  M''''''M:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::HMMMM''''''''''''''''''''''''''''''''MM");
        System.out.println("                                  M''''''M:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::MMM M''''''''''''''''''''''''''''''''MM");
        System.out.println("                                  M'''''.H::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::MM   :M''''''''''''''''''''''''''''''''M");
        System.out.println("                                 M.'''''M::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::HM     M''''''''''''''''''''''''''''''''M");
        System.out.println("                                 M''''''M::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M      'M'''''''''''''''''''''''''''''''.'");
        System.out.println("                                 M''''''M:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M::      .M'''''''''''''''''''''''''''''''M");
        System.out.println("                                M'''''''MMI::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::H::M         M'''''''''''''''''''''''''''''M.");
        System.out.println("                                M''''''''''MM:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M:::M          'M'M''''''''''''''''''''''''''M.");
        System.out.println("                                M.'''''''''''MM::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M::::M            M:M''''''''''''''''''''''''''MM");
        System.out.println("                                 M'''''''''''''MM:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M             HM''''''''''''''''''''''''''''MM");
        System.out.println("                                 M.''''''''''''''M:::::::::::::::::MMMMM::MM::::::::::::::::::::::::::::::::::::::::::::MM               M.''''''''''''''''''''''''''''MM");
        System.out.println("                                 'M''''''''''''''''MM::::::::::::OMM '  M   MM:HMMMMMMMMMMI:::::::::::::::::::::::::::MM                 MM'''''''''''''''''''''''''''''OM");
        System.out.println("                                 M'''''''''''''''''MMMMMMMMM'     M MM M   M .M                   '::'H:HMMMMM:::::MM.                   ::''''''''''''''''''''''''''''''M");
        System.out.println("                                 :''''''''''''''''''MM           M  H  '  MM   M :'...H                        'MMH                      M:'''''''''''''''''''''''''''''''M");
        System.out.println("                                M''''''''''''''''''MMM      HMM: M    M  MMMM     MMM.'                          M                       MM'''''''''''''''''''''''''''''''M:");
        System.out.println("                               'M''''''''''''''''''''MMMMO      MM  M   .M MMH   M                                M                      MM'''''''''''''''''''''''''''''''.M");
        System.out.println("                               M:'''''''''''''''''''MM:           HH    M:  MM   M'                              M                       .M''''''''''''''''''''''''''''''''M");
        System.out.println("                               M''''''''''''''''''''MM       MMM  M  M   :   M:  I:::::::::MOHMMMM'             M                         MM'''''''''''''''''''''''''''''''M'");
        System.out.println("                               M''''''''''''''''''''':MHMO:::::  ':HMM:H:M   .M   M:::::::::M::::::::::M::IMMM M                           MM''''''''''''''''''''''''''''''MM");
        System.out.println("                               M'''''''''''''''''''''M::::::::M  O  :::::M:   M   M::::::::::M::::::::::M:::::HM                            MM''''''''''''''''''''''''''''':M");
        System.out.println("                               M'''''''''''''''''''':M::::::::H  M H::::::M   M   M:::::::::::M:::::::::HM:::::MM                            MM'''''''''''''''''''''''''''''M");
        System.out.println("                               M''''''''''''''''''''M::::::::M   M M::::::M   MO  ':::::::::::MM:::::::::M:::::::M                            MM''''''''''''''''''''''''''''MM");
        System.out.println("                               M'''''''''''''''''''M:::::::::M  H  M::::::M    M   M:::::::::::M::::::::::H::::::MM                            MM'''''''''''''MMMMMMMMMMMMMMMMMM");
        System.out.println("                               HM'''''''''''''''''HM:::::::::   M  M::::::M    M   M::::::::::::M:::::::::M:::::::M                             M'''''''''' MMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                MMMMMMMMMMMMMMMMMMM:::::::::M   M  H::::::M    M   M::::::::::::H:::::::::M:::::::MM                             M''''''HMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                               HMMMMMMMMMMMMMMMMMMM:::::::::   M'  M:::::::         M::::::::::::M:::::::::::::::::M                              M''''MMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                MMMMMMMMMMMMMMMMMM:::::::::M   M   ::::::::M    .   M:::::::::::::M::::::::::::::::.M                              M'MMMMMMMMMMMMMMMMMMMMMMMMMMM.");
        System.out.println("                                MMMMMMMMMMMMMMMMMMH::::::::M   M  '::::::::M    M   M:::::::::::::H:::::::::::::::::MH                              MMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                               'MMMMMMMMMMMMMMMMMM:::::::::M   :  :::::::::M    M    M:::::::::::::::::::::::::::::::M                             MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                               MMMMMMMMMMMMMMMMMMM:::::::::    .  M::::::::M    '    M::::::::::::::::::::::::::::::::M                            'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                               MMMMMMMMMMMMMMMMMMM::::::::M   M   M::::::::M         M:::::::::::::::::::::::::::::::::'                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                               MMMMMMMMMMMMMMMMMMM::::::::M   M   M::::::::M         M:::::::::::::::::::::::::::::::::M                             MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                               MMMMMMMMMMMMMMMMMMM::::::::M   M   M::::::::M          ::::::::::::::::::::::::::::::::::M                            MMMMMMMMMMMMMMMMMMMMMMMMMMMMMH");
        System.out.println("                               MMMMMMMMMMMMMMMMMMM::::::::    H   M::::::::M          M:::::::::::::::::::::::::::::::::M                             MMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                              :MMMMMMMMMMMMMMMMMMM:::::::H    '   H::::::::M          M::::::::::::::::::::::::::::::::::M                             MMMMMMMMMMMMMM:''''''''''M");
        System.out.println("                               MMMMMMMMMMMMMMMMMMM:::::::M        :::::::::M          M:::::::::::::::::::::::::::::::::::M                             MMMMMM.''''''''''''''''''.");
        System.out.println("                                MMM:''''''''MMMMMM:::::::M   M   .:::::::::M'          O:::::::::::::::::::::M:::::::::::::M                             M'''''''''''''''''''''''M");
        System.out.println("                                M'''''''''''''''MM:::::::M       M:::::::::M           M:::::::::::::::::::::M:::::::::::::M                            M''''''''''''''''''''''''M");
        System.out.println("                                M''M''''''''''''MM:::::::        M:::::::::M           H:::::::::::::::::::::H:::::::::::::M.                         MM'''''''''''''''''''''''''.M");
        System.out.println("                                M''M''''''''''''M::::::::        ::::::::::M.          M:::::::::::::::::::::H::::::::::::H:::                      MM'''''''''''''''''M''''''''''M");
        System.out.println("                               M.''M''''''''''''M:::::::M        .:::::::::M.          H::::::::::::::::::::::::::::::::::H::M                      M'''''''''''''''''''M'''''''''M");
        System.out.println("                               M'''M'''''''''''M::::::::M         :::::::::M.           ::::::::::::::::::::M:::::::::::::M::MM                     :'''''''''''''''''''M''''''''':");
        System.out.println("                               M'''M''''''''''MH::::::::M        ':::::::::M'           M:::::::::::::::::::M:::::::::::::M::M:M                     M'''.M''''''''M'''''''''''''''M");
        System.out.println("                               :''M''''''''''MM:::::::::'        '::::::::::M           M:::::::::::::::::::M:::::::::::::I:::::M                    M''''M''''''''M'''''M'''''''''M");
        System.out.println("                              M'''M'''''''''MM::::::::::          ::::::::::M           'H:::::::::::::::::M::::::::::::::::::::HM                   'M''''M'''''''M'''''M''''':'''M");
        System.out.println("                              M''''''''''''MM''H:::::::M         :::::::::::M            M:::::::::::::::::M:::::::::::::::::::::HM                   M'MMM:'''''''M'''''M'''''''''M");
        System.out.println("                              M''O'''''''IM'' :M:::::::M         :::::::::::M            M:::::::::::::::::M::::::::::::::::::::::M:                  M''''''''''''M''''''''''''MMM");
        System.out.println("                             M'''' M''''' ''''MM:::::::M          M:::::::::M          MMH::::::::::::::::M:::::M::::::::::::::::::M                  MM'''M''''''''M'''''M''''M");
        System.out.println("                             MM''MM'M''''M  M'MM:::::::M          H:::::::::M       .M::::::::::::::::::::M::::M::::::::::::::::::::M                    M'M:'''''''M''''MMMMMM");
        System.out.println("                              MM'':''''M'.''M:'M:::::::M          ::::::::::M      ::::::::::::::::::::::H:::::H:::::::::::::::::::::M                    M'M''''''''''''M");
        System.out.println("                               .M'''''':M''H'''M:::::::M MM:::::MMM:::::::::M    M:::::::::::::::::::::::M::::M::::::::::::::::::::::OM                   :M'''''''MMMMMM");
        System.out.println("                                HM'''MM'M''M'''M:::::::M::::::::::::::::::::M   M:::::::::::::::::::::::HM:::M::::::::::::::::::::::::MM                    :''''MM");
        System.out.println("                                  MMMMMM''M MMMM::::::::::::::::::::::::::::M MM::::::::::::::::::::::::M::::M:::::::::::::::::::::::::MM                   'MMM");
        System.out.println("                                               M::::::::::::::::::::::::::::MHH:::::::::::::::::::::::::M:::M:::::::::::::::::::::::::::M.");
        System.out.println("                                              'M::::::::::::::::::::::::::::MMMM:::::::::::::::::::::::M:::M:::::::::::::::::::::::::::::M");
        System.out.println("                                              HM::::::::::::::::::::::::::::::MM:::::::::::::::::::::::M::OH::::::::::::::::::::::::::::::M");
        System.out.println("                                              MH:::::::::::::::::::::::::::::::M::::::::::::::::::::::M:::M:::::::::::::::::::::::::::::::M");
        System.out.println("                                              M::::::::::::::::::::::::::::::::M:::::::::::::::::::::OM::M::::::::::::::::::::::::::::::::M");
        System.out.println("                                              M::::::::::::::::::::::::::::::::MM::::::::::::::::::::M::MH::::::::::::::::::::::::::::::::M");
        System.out.println("                                              M::::::::::::::::::::::::::::::::OM::::::::::::::::::::M::M:::::::::::::::::::::::::::::::::MH'");
        System.out.println("                                              M::::M::::::::::::::::::::::::::::MM:::::::::::::::::::::M::::::::::::::::::::::::::::::::::M::M");
        System.out.println("                                              M::::M::::::::::::::::::::::::::::MM::::::::::::::::::::M::::::::::::::::::::::::::::::::::MM:::M");
        System.out.println("                                              M::::MH::::::::::::::::::::::::::::MH:::::::::::::::::::M::::::::::::::::::::::::::::::::::M::::I");
        System.out.println("                                              M::::HM::::::::::::::::::::::::::::MM::::::::::::::::::::::::::::::::::::::::::::::::::::::M::::.");
        System.out.println("                                             'M:::::M::::::::::::::::::::::::::::M:::::::::::::::::::::::::::::::::::::::::::::::::::::::M:::H");
        System.out.println("                                             MM:::::M:::::::::::::::::::::::::::::M::::::::::::::::::::::::::::::::::::::::::::::::::::::M:::OM");
        System.out.println("                                             MM:::::MH::::::::::::::::::::::::::::HH::::::::::::::::::::::::::::::::::::::::::::::::::::MM:::MMM");
        System.out.println("                                             MH::::::M::::::::::::::::::::::::::::MM::::::::::::::::::::::::::::::::::::::::::::::::::::M::::M:MM");
        System.out.println("                                             MH::::::M::::::::::::::::::::::::::::IM::::::::::::::::::::::::::::::::::::::::::::::::::::M::::M::M");
        System.out.println("                                             MH:::::::M:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M::::M:::M:");
        System.out.println("                                             MH:::::::M::::::::::::::::::::::::::::M:::::::::::::::::::::::::::::::::::::::::::::::::::MM:::MM:::IM'");
        System.out.println("                                            'M::::::::HH:::::::::::::::::::::::::::.M::::::::::::::::::::::::::::::::::::::::::::::::::MH:::MM::::HMM");
        System.out.println("                                            IM:::::::::M:::::::::::::::::::::::::::HM::::::::::::::::::::::::::::::::::::::::::::::::::M::::M::::::MM:");
        System.out.println("                                            MM:::::::::H:::::::::::::::::::::::::::HM::::::::::::::::::::::::::::::::::::::::::::::::::M::::M::::::::M'");
        System.out.println("                                            MM::::::::::M:::::::::::::::::::::::::::M:::::::::::::::::::::::::::::::::::::::::::::::::HM::::M::::::::MM");
        System.out.println("                                            MM::::::::::MM::::::::::::::::::::::::::M:::::::::::::::::::::::::::::::::::::::::::::::::MH::::M::::::::.MM");
        System.out.println("                                            M::::::::::::M::::::::::::::::::::::::::MM::::::::::::::::::::::::::::::::::::::::::::::::M::::IM:::M:::::HMM");
        System.out.println("                                            M:::::::::::::M::::::::::::::::::::::::::M::::::::::::::::::::::::::::::::::::::::::::::::M:::::M:::M:::::::M.");
        System.out.println("                                           'M:::::::::::::MM:::::::::::::::::::::::::M:::::::::::::::::::::::::::::::::::::::::::::::::::::M::::MI::::::MM");
        System.out.println("                                           MH::::::::::::::MO::::::::::::::::::::::::M:::::::::::::::::::::::::::::::::::::::::::::::::::::M:::::M:::::::M");
        System.out.println("                                           MM:::::::::::::::M::::::::::::::::::::::::H::::::::::::::::::::::::::::::::::::::::::::::::::::HM:::::M:::::::MM");
        System.out.println("                                           M::::::::::::::::MM:::::::::::::::::::::::.::::::::::::::::::::::::::::::::::::::::::::::::::::M::::::M::::::::M");
        System.out.println("                                           M:::::::::::::::::M:::::::::::::::::::::::HM::::::::::::::::::::::::::::::::::::::::::::::::::HM::::::M:::::::::M");
        System.out.println("                                           M::::::::::::::::::MH::::::::::::::::::::::M::::::::::::::::::::::::::::::::::::::::::::::::::M:::::::M:::::::::M.");
        System.out.println("                                          :M::::::::::::::::::::::::::::::::::::::::::M:::::::::::::::::::::::::::::::::::::::::::::::::MM:::::::M::::::::::M");
        System.out.println("                                          'M::::::::::::::::::::::::::::::::::::::::::M:::::::::::::::::::::::::::::::::::::::::::::::::M::::::::M::::::::::M");
        System.out.println("                                           MH:::::::::::::::::::::::::::::::::::::::::M::::::::::::::::::::::::::::::::::::::::::::::::MM:::::::::::::::::::M");
        System.out.println("                                            MM::::::::::::::::::::::::::::::::::::::::HM::::::::::::::::::::::::::::::::::::::::::::::HM:::::::::H:::::::::M");
        System.out.println("                                             MM::::::::::::::::::::::::::::::::::::::::MM:::::::::::::::::::::::::::::::::::::::::::::MM::::::::M::::::::::M");
        System.out.println("                                              HM::::::::::::::::::::::::::::::::::::::::HMH::::::::::::::::::::::::::::::::::::::::::MM:::::::::M::::::::::M");
        System.out.println("                                               .MH:::::::::::::::::::::::::::::::::::::::HMM::::::::::::::::::::::::::::::::::::::::HMM:::::::::M:::::::::M");
        System.out.println("                                                 MM::::::::::::::::::::::::::::::::::::::MMMMMM:::::::::::::::::::::::::::::::::::::MH::::::::::M:::::::::M");
        System.out.println("                                                  MM::::::::::::::::::::::::::::::::::::MM:::MMMH::::::::::::::::::::::::::::::::::::::::::::::MM::::::::::");
        System.out.println("                                                   MMH:::::::::::::::::::::::::::::::::MM:::::M: MM::::::::::::::::::::::::::::::::::::::::::::M:::::::::M");
        System.out.println("                                                   MMMM::::::::::::::::::::::::::::::MMI::::::M  MMMM:::::::::::::::::::::::::::::::::::::::::M::::::::::M");
        System.out.println("                                                  MM:MMM:::::::::::::::::::::::::::MMM::::::::M  'M::MH:::::::::::::::::::::::::::::::::::::::M::::::::::H");
        System.out.println("                                                  HM:::MMM:::::::::::::::::::::::IMM::::::::::M   M::::MM::::::::::::::::::::::::::::::::::::MM:::::::::M");
        System.out.println("                                                  IM::::MMM:::::::::::::::::::::MM::::::MM:::M     ::::::MM::::::::::::::::::::::::::::::::::MO:::::::::M");
        System.out.println("                                                  MM::::::MMM:::::::::::::::::MM:::::::M:M:::M     M:::::::MM:::::::::::::::::::::::::::::::MM:::::::::M");
        System.out.println("                                                  MM::::::MOMM::::::::::::::MM::::::::M::::::M     M:::::::::HM:::::::::::::::::::::::::::::MM:::::::::M");
        System.out.println("                                                  MM::::::M::IMM:::::::::MMM::::::::HM:::::::M     .:::::::::::MM::::M:::::::::::::::::::::HM:::::::::M");
        System.out.println("                                                  MM::::::M::::MM::::::M:::::::::::MM::::::::M     I:::::::::::::MM::::M:::::::::::::::::::M::::::::::M");
        System.out.println("                                                  MH::::::M:::::MM::::::::::::::::MM:::::::::M      O::::::::::::::M::::MM::::::::::::::::HM:::::::::M");
        System.out.println("                                                  MM::::::MH:::::M:::::::::::::::MI::::::::OMH      'M::::::::::::::MH::::MM::::::::::::::M:::::::::HM");
        System.out.println("                                                  MM:::::::M:::::H::::::::::::::M::::::::HMH           MM::::::::::::H::::::M:::::::::::::::::::::::M'");
        System.out.println("                                                   MM::::::M::::::::::::::::::HM::::::::M'               MM:::::::::::H::::::MM:::::::::::::::::::::M");
        System.out.println("                                                    MM:::::H::::::::::::::::::M::::::MM                     MI:::::::::::::::::MM::::::::::::::::::MM");
        System.out.println("                                                     MM:::::M::::::::::::::::M:::::MM                         MM::::::::::::::::MMM::::::::::::::::M");
        System.out.println("                                                       MH::::M::::::::::::::M::HMMMM                            MMM:::::::::::::::MMM:::::::::::::MM'");
        System.out.println("                                                        MMMMMMMMMMMMMMMMMMMMMMMMMMMM                              'MM::::::::::::::MMMMM:::::::::MMM");
        System.out.println("                                                         MMMMMMMMMMMMMMMMMMMMMMMMMMM                                 MM:::::::::::::MMMM:::MMMMMMMMM");
        System.out.println("                                                          MMMMMMMMMMMMMMMMMMMMMMM.M                                   :MMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                                           M''''''''''''''''''''''MM                                   MMMMMMMMMMMMMMMMMMMMMMMMMMM'M");
        System.out.println("                                                           M'''''''''''''''''''''''M                                    MMMMMMMMMMMMMMMMMMMMMMM:'''''");
        System.out.println("                                                         O''''''''''''''''''''''''''                                     MMMMMMMMMM.I.''''''''''''''M");
        System.out.println("                                                         H''M'''''''''''''''''''''''M                                     M''''''''''''''''''''''''''M");
        System.out.println("                                                        MM'''' :MM'''''''''''''''''''M                                   'M''.MH:''''''''''''''''''''M");
        System.out.println("                                                     MM'''''''''''''''''''''''''''''HM                                   .M.''''''''''''''''''''''''''M");
        System.out.println("                                                  MM:''''''''''''''''''''''''''''''MMMM                                  MM'''''''''''''''''''''''''''M");
        System.out.println("                                               MMMMMMM'''''''''''''''''''''''''' MMMMMM                                 'M'''''''IHMMMMMMMM '''''''''''M");
        System.out.println("                                            MMMMMMMMMMM:'''''''''''''''''''''HMMMMMMMMM                                 MH'':MMMMMMMMMMMMMMMMM'''''''''M");
        System.out.println("                                         'MMMMMMMMMMMMMMMH''''''''''HMMMMMMMMMMMMMMMMMMM                               OM'MMMMMMMMMMMMMMMMMMMMMH'''''''MM");
        System.out.println("                                       MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                               M'MMMMMMMMMMMMMMMMMMMMMMMM '''''MM");
        System.out.println("                                    'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                               MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:");
        System.out.println("                                    MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                              MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                               MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM.                                 MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                   MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM:                                     'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                    .MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM                                               HMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMH");
        System.out.println("                                           'MMMMMMMMMM:                                                             MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                                                                                                     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                                                                                                     MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM");
        System.out.println("                                                                                                                     MMMMMMMMMMMMMMMMMMMMMMMMMMMM.");
        System.out.println("                                                                                                                      MMMMMMMMMMMMMMMMMMMMM");
    }
}
